
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hukukProjesi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Author
{

    public int Id { get; set; }

    public string NameSurname { get; set; }

    public string About { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public Nullable<System.DateTime> AddedDate { get; set; }

    public string AddedBy { get; set; }

    public Nullable<System.DateTime> ModifyDate { get; set; }

    public string ModifyBy { get; set; }

    public string image { get; set; }

    public string Role { get; set; }

    public Nullable<int> Deneyim { get; set; }

    public string Egitim { get; set; }

    public string Aciklama { get; set; }

}

}
