
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hukukProjesi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Blog
{

    public int BlogId { get; set; }

    public string Baslik { get; set; }

    public string Ozet { get; set; }

    public string Konu { get; set; }

    public Nullable<System.DateTime> EklenmeTarihi { get; set; }

    public Nullable<System.DateTime> DüzenlenmeTarihi { get; set; }

    public string image { get; set; }

    public string EkleyenKisi { get; set; }

}

}
